# Controller generated by Typus, use it to extend admin functionality.
class Admin::DaywisemenusController < Admin::MasterController

=begin

  ##
  # You can overwrite and extend Admin::MasterController with your methods.
  #
  # Actions have to be defined in <tt>config/typus/application.yml</tt>:
  #
  #   Daywisemenu:
  #     actions:
  #       index: custom_action
  #       edit: custom_action_for_an_item
  #
  # And you have to add permissions on <tt>config/typus/application_roles.yml</tt> 
  # to have access to them.
  #
  #   admin:
  #     Daywisemenu: create, read, update, destroy, custom_action
  #
  #   editor:
  #     Daywisemenu: create, read, update, custom_action_for_an_item
  #

  def index
  end

  def custom_action
  end

  def custom_action_for_an_item
  end

=end




	  def list
		@daywisemenus = Daywisemenu.find(:all)
		#@days = Day.find(:all)
		
	end

 def new
	   @daywisemenu = Daywisemenu.new
      @days = Day.find(:all)

   end
   
   def create
	   
	@daywisemenu = Daywisemenu.new(params[:daywisemenu])
      if @daywisemenu.save
            redirect_to :action => 'list'
      else
            @days = Day.find(:all)
            render :action => 'new'
      end

	
end


   def edit
	   
	  @daywisemenu = Daywisemenu.find(params[:id])
      @days = Day.find(:all)   
	   
   end
   def update
	      @daywisemenu = Daywisemenu.find(params[:id])
      if @book.update_attributes(params[:book])
         redirect_to :action => 'show', :id => @daywisemenu
      else
         @days = Day.find(:all)
         render :action => 'edit'
      end

   end

def show
	   @daywisemenu = Daywisemenu.find(params[:id])

   end


end